export const googleFonts = [
  { name: 'Roboto', category: 'sans-serif' },
  { name: 'Open Sans', category: 'sans-serif' },
  { name: 'Lato', category: 'sans-serif' },
  { name: 'Montserrat', category: 'sans-serif' },
  { name: 'Oswald', category: 'sans-serif' },
  { name: 'Source Sans Pro', category: 'sans-serif' },
  { name: 'Slabo 27px', category: 'serif' },
  { name: 'Raleway', category: 'sans-serif' },
  { name: 'PT Sans', category: 'sans-serif' },
  { name: 'Merriweather', category: 'serif' },
  { name: 'Roboto Condensed', category: 'sans-serif' },
  { name: 'Roboto Mono', category: 'monospace' },
  { name: 'Noto Sans', category: 'sans-serif' },
  { name: 'Poppins', category: 'sans-serif' },
  { name: 'Ubuntu', category: 'sans-serif' },
  { name: 'Playfair Display', category: 'serif' },
  { name: 'PT Serif', category: 'serif' },
  { name: 'Lora', category: 'serif' },
  { name: 'Nunito', category: 'sans-serif' },
  { name: 'Nunito Sans', category: 'sans-serif' },
  { name: 'Fira Sans', category: 'sans-serif' },
  { name: 'Quicksand', category: 'sans-serif' },
  { name: 'Work Sans', category: 'sans-serif' },
  { name: 'Dosis', category: 'sans-serif' },
  { name: 'Rubik', category: 'sans-serif' },
  { name: 'Oxygen', category: 'sans-serif' },
  { name: 'Mukta', category: 'sans-serif' },
  { name: 'Heebo', category: 'sans-serif' },
  { name: 'Cabin', category: 'sans-serif' },
  { name: 'Bitter', category: 'serif' },
  { name: 'Arimo', category: 'sans-serif' },
  { name: 'Proza Libre', category: 'sans-serif' },
  { name: 'Varela Round', category: 'sans-serif' },
  { name: 'Anton', category: 'display' },
  { name: 'Pacifico', category: 'handwriting' },
  { name: 'Exo 2', category: 'sans-serif' },
  { name: 'Lobster', category: 'display' },
  { name: 'Bree Serif', category: 'serif' },
  { name: 'Josefin Sans', category: 'sans-serif' },
  { name: 'Yanone Kaffeesatz', category: 'sans-serif' },
  { name: 'Abel', category: 'sans-serif' },
  { name: 'Shadows Into Light', category: 'handwriting' },
  { name: 'Dancing Script', category: 'handwriting' },
  { name: 'Fjalla One', category: 'sans-serif' },
  { name: 'Indie Flower', category: 'handwriting' },
  { name: 'Caveat', category: 'handwriting' },
  { name: 'Crimson Text', category: 'serif' },
  { name: 'Amatic SC', category: 'handwriting' },
  { name: 'Architects Daughter', category: 'handwriting' },
  { name: 'Permanent Marker', category: 'display' },
  { name: 'Satisfy', category: 'handwriting' },
  { name: 'Comfortaa', category: 'display' },
  { name: 'Patua One', category: 'display' },
  { name: 'Righteous', category: 'display' },
  { name: 'Cinzel', category: 'serif' },
  { name: 'Great Vibes', category: 'handwriting' },
  { name: 'Sacramento', category: 'handwriting' },
  { name: 'Tangerine', category: 'handwriting' },
  { name: 'Cookie', category: 'handwriting' },
  { name: 'Kaushan Script', category: 'handwriting' },
  { name: 'Press Start 2P', category: 'display' },
  { name: 'Bangers', category: 'display' },
  { name: 'Fredoka One', category: 'display' },
  { name: 'Alfa Slab One', category: 'display' },
  { name: 'Passion One', category: 'display' },
  { name: 'Ultra', category: 'serif' },
  { name: 'Monoton', category: 'display' },
  { name: 'Cormorant Garamond', category: 'serif' },
  { name: 'EB Garamond', category: 'serif' },
  { name: 'Zilla Slab', category: 'serif' },
  { name: 'Noticia Text', category: 'serif' },
  { name: 'IBM Plex Sans', category: 'sans-serif' },
  { name: 'IBM Plex Mono', category: 'monospace' },
  { name: 'Space Mono', category: 'monospace' },
  { name: 'Inconsolata', category: 'monospace' },
  { name: 'Source Code Pro', category: 'monospace' },
  { name: 'VT323', category: 'monospace' },
  { name: 'Cutive Mono', category: 'monospace' },
  { name: 'Nanum Gothic Coding', category: 'monospace' },
  { name: 'Share Tech Mono', category: 'monospace' },
  { name: 'Anonymous Pro', category: 'monospace' },
  { name: 'BioRhyme', category: 'serif' },
  { name: 'Cardo', category: 'serif' },
  { name: 'Concert One', category: 'display' },
  { name: 'Damion', category: 'handwriting' },
  { name: 'Forum', category: 'display' },
  { name: 'IM Fell English SC', category: 'serif' },
  { name: 'Jura', category: 'sans-serif' },
  { name: 'Kreon', category: 'serif' },
  { name: 'Marck Script', category: 'handwriting' },
  { name: 'Merienda', category: 'handwriting' },
  { name: 'Philosopher', category: 'sans-serif' },
  { name: 'Play', category: 'sans-serif' },
  { name: 'Quantico', category: 'sans-serif' },
  { name: 'Quattrocento', category: 'serif' },
  { name: 'Rokkitt', category: 'serif' },
  { name: 'Special Elite', category: 'display' },
  { name: 'Syncopate', category: 'sans-serif' },
  { name: 'Volkhov', category: 'serif' },
  { name: 'Vollkorn', category: 'serif' },
];
